### ISSUE TITLE
No TIDL Delegate in tutorial_classification and tutorial_detection

### ISSUE THREAD

**Issue by IsidoraR** [TexasInstruments/edgeai-benchmark#7]
Hi,
In the tutorial_classification and tutorial_detection notebooks, why isn't TIDL_delegate used to calibrate the models for 8-bit fixed-point inference?

**Comment by mathmanu** [comment]
Why do you say: why isn't TIDL_delegate used to calibrate the models for 8-bit fixed-point inference
By default 8-bit tidl_offload is used. 

If you wish to change it, these flags can be changed:
https://github.com/TexasInstruments/edgeai-benchmark/blob/master/settings_base.yaml#L79
https://github.com/TexasInstruments/edgeai-benchmark/blob/master/settings_base.yaml#L12
